spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MVCC=true;LOCK_TIMEOUT=10000
    // url: jdbc:h2:tcp://localhost/~/test;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MVCC=true
    username: sa
    password:
    driver: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

